# Generated by Django 4.2.3 on 2023-08-03 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(default='기관명', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('deadline', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=300)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='media/Post')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
