# Generated by Django 4.2.4 on 2023-08-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_performancepost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancepost',
            name='name',
        ),
    ]
