# Generated by Django 4.2.3 on 2023-08-03 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=254)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='media/Resume')),
                ('age', models.PositiveIntegerField(default=17)),
                ('education', models.CharField(max_length=254)),
                ('career', models.CharField(max_length=254)),
                ('award', models.CharField(max_length=254)),
                ('introduce', models.CharField(max_length=254)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consum_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
