# Generated by Django 4.2.3 on 2023-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_alter_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(default='무관', max_length=50),
        ),
    ]
