# Generated by Django 4.2.4 on 2023-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_resume_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='이름', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Resume/'),
        ),
    ]
